[package]
name = "radio-sx127x"
description = "Rust driver for the Semtec SX127x Sub GHZ LoRa Radio ICs"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[dependencies]
embedded-hal = { git="https://github.com/japaric/embedded-hal", features=["unproven"] }
futures = "0.1.22"
nb = "0.1.1"
radio = { path = "../rust-radio" }
libc = "0.2.42"

[build-dependencies]
bindgen = "0.26.3"
cc = "1.0"
