[package]
name = "radio-sx1726"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[dependencies]
embedded-hal = { git="https://github.com/japaric/embedded-hal", feature="unproven" }
futures = "0.2.1"
nb = "0.1.1"
radio = { path = "../rust-radio" }
