[package]
name = "radio-sx127x"
description = "Rust driver for the Semtec SX127x Sub GHZ LoRa Radio ICs"
version = "0.10.1"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
repository = "https://github.com/ryankurte/rust-radio-sx127x"
license = "MPL-2.0"

[package.metadata.commands]
docker-build = "docker run --rm -it -v`pwd`:/work -v$HOME/.cargo/registry:/root/.cargo/registry ryankurte/rust-embedded /bin/bash -c \"cd /work && cargo build --target armv7-unknown-linux-gnueabihf\""

[features]
util = [ "structopt", "linux-embedded-hal", "simplelog", "humantime" ] 
default = [ "util", "serde" ]

[dependencies]
libc = "0.2.42"
log = { version = "0.4.6" }
bitflags = "1.0.4"
radio = "0.4.0"
embedded-hal = { version = "0.2.3", features = ["unproven"] }
embedded-spi = { version = "0.5.1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"], optional=true }

structopt = { version = "0.2.15", optional = true }
linux-embedded-hal = { version = "0.2.2", optional = true }
simplelog = { version = "0.7.3", optional = true }
humantime = { version = "1.2.0", optional = true }

[dev-dependencies]
color-backtrace = "0.1.3"

[[bin]]
name = "sx127x-util"
path = "src/util/main.rs"
required-features = ["util"]

[[test]]
name = "integration"
path = "tests/integration.rs"
required-features = ["utils"]
